---
title: "MDSR Context"
output: github_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ohio Voter Demographics (Context)

Voter participation is the bedrock of American democracy. In order to understand who votes and how, we can look either at estimates derived from samples in studies like The Cooperative Congressional Elections Study (CCES), which rely on self reporting but cover a broad range of topics, or directly looking at voter files, which though completely accurate give us much less information. Demographic information can help predict voting behavior, especially in key swing states like Ohio but this is only true if the representative samples are, in fact, representative. Do people, when asked, over report their voting habits?

Ohio does not collect any demographic information other than age when residents register to vote. Even with this limited information, we can look at whether the age range represented in the CCES accurately reflects the age range of Ohio voters. Who votes in Ohio and who says they vote? Are representative samples of the state actually representative? How reflective are surveys like CCES at all?