---
title: "Messing_with_age_Carter"
output: github_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(mdsr)




library(lubridate)
```

## adding an age variable

```{r}
#download file from https://drive.google.com/a/reed.edu/uc?export=download&confirm=vfYf&id=0B16R3n7VKQteeEh5SmozTXRVb2s

# make sure Ohio_df_lite.csv is in Downloads

Ohio_df_lite <- read_csv("~/Downloads/Ohio_df_lite.csv", na = c("", "NA"))

#mutate to make an age variable

Ohio_df_lite <- mutate(Ohio_df_lite, age = 2017 - year(DATE_OF_BIRTH))

#I checked the df using unique. I see age 18 and 19 which is a good sign. I see some 137, 135, and 132 year olds which is bad.

unique(Ohio_df_lite$age)

#gonna filter out everyone above 140
Ohio_under120 <- filter(Ohio_df_lite, age < 120)

#to make a list of everyone over 120 (and try and fix it) unhash this
#Ohio_over120 <- filter(Ohio_df_lite, age > 120)
```

```{r}
#i want to see how age is distributed, before and after removing the roughly 8000 people over the age of 140
#full set
ggplot(Ohio_df_lite, aes(age)) + geom_density(kernel = "gaussian")
#under 140
ggplot(Ohio_under120, aes(age)) + geom_density(kernel = "gaussian")
```
